### ISSUE TITLE
As a user I would like to have an REST endpoint to create a TrackitUser

### ISSUE THREAD

**Issue by florin-grozea-old** [flgor/trackit#5]
- Create a new TrackitUser controller (request mapping /trackitUser)
- Add a method for creating a user (HttpMethod.POST, request mapping "")
- Add a test to prove the user was created.

**Comment by ioangrozea** [comment]
I will start work on this.

**Comment by ioangrozea** [comment]
I will use @RestController annotation and i will create new dto class CreateTrackitUserDto.

**Comment by florin-grozea-old** [comment]
Nice done @ioangrozea 
gg
